services:
  server:
    image: dev_env:server
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./_env/dev/server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api:/api:ro
    networks:
      - lab08_task-internal
    depends_on:
      - api
  api:
    image: dev_env:php_84
    container_name: api
    volumes:
      - ./api:/app
    networks:
      - lab08_task-internal
    depends_on:
      - cache
      - db
  cache:
    image: redis:7-alpine
    container_name: cache
    networks:
      - lab08_task-internal
  db:
    image: mysql:8
    container_name: db
    volumes:
      - ./_env/.database:/var/lib/mysql
    networks:
      - lab08_task-internal
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab08
      MYSQL_USER: lab08
      MYSQL_PASSWORD: lab08


networks:
  lab08_task-internal:
    driver: bridge

