POST http://localhost/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "test1@lab08.test",
  "password": "password-1"
}

###

POST http://localhost/api/admin/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@lab08.com",
  "password": "admin123"
}